FORMAT: 1A
HOST: http://www.exacttargetapis.com/

# ExactTarget API Specifications - Prototype
Prototype of ExactTarget APIs.

# Group Account Resource

## Account Messages Transactional Collection [/accounts/{mid}/messages/transactional{?pageSize,count}]

Information about Messages sent by an account.

+ Model (application/json)
    JSON Representation of Messages that have been created by an Account
    + Body
    
            {
                "_links": {
                    "self": { "href": "/accounts/{id}/messages/transactional" },
                    "parent": { "href": "/accounts/{id}" },
                    "next" : { "href": "/accounts/{id}/messages/transactional?pageSize=25&count=0" },
                    "prev" : { "href": "/accounts/{id}/messages/transactional?pageSize=25&count=50" },
                    "search" : { "verb" : "POST", "href" : "/account/{id}/messages/transactional", "parameters" : "query" }
                },
                "id": "{id}",
                "count": 134, 
                "active" : 32,
                "paused" : 7,
                "stopped" : 12,
                "deleted" : 38,
                "new" : 14,
                "page": 2,
                "pageSize": 25,
                "messages" : [
                  { "id" : 25, "message_data" : "..." },
                  { "id" : 26, "message_data" : "..." },
                  { "id" : 27, "message_data" : "..." },
                  { "id" : 28, "message_data" : "..." },
                  { "id" : 29, "message_data" : "..." },
                  { "id" : 30, "message_data" : "..." },
                  { "id" : 31, "message_data" : "..." },
                  { "id" : 32, "message_data" : "..." },
                  { "id" : 33, "message_data" : "..." },
                  { "id" : 34, "message_data" : "..." },
                  { "id" : 35, "message_data" : "..." },
                  { "id" : 36, "message_data" : "..." },
                  { "id" : 37, "message_data" : "..." },
                  { "id" : 38, "message_data" : "..." },
                  { "id" : 39, "message_data" : "..." },
                  { "id" : 40, "message_data" : "..." },
                  { "id" : 41, "message_data" : "..." },
                  { "id" : 42, "message_data" : "..." },
                  { "id" : 43, "message_data" : "..." },
                  { "id" : 44, "message_data" : "..." },
                  { "id" : 45, "message_data" : "..." },
                  { "id" : 46, "message_data" : "..." },
                  { "id" : 47, "message_data" : "..." },
                  { "id" : 48, "message_data" : "..." },
                  { "id" : 49, "message_data" : "..." }
                ]
                
            }


+ Parameters
    + mid (required) ... MID for the account
    + pageSize (optional, number, `100`) ... number of records to return, default 100 
    + count (optional, number `300`) ... offset of records to return
    
### Retrieve Transactional Messages for an Account [GET]

+ Response 200
    [Account Messages Transactional Collection][]

## Account Events [/accounts/{mid}/events{?fields,startDate,endDate}]
A collection of all events that have occurred for an account, total.

+ Model (application/json)
    JSON Representation of events that have occurred on an Account, rolled up daily
    + Body
    
            {
                "_links": {
                    "daily": { "href": "/accounts/{id}/events/daily{?fields,startDate,endDate}"},
                    "hourly": { "href": "/accounts/{id}/events/hourly{?fields,startDate,endDate}"},
                    "self": { "href": "/accounts/{id}/events{?fields,startDate,endDate}" },
                    "parent": { "href": "/accounts/{id}" }
                },
                "id": "{id}",
                "toSend": 18714,
                "delivered": { "total" : 18500, "percent" : 98.85 },
                "bounces" : { "total" : 164, "hard" : 14, "soft" : 100, "blocked" : 50 },
                "opened" : { "unique" : 18333 },
                "clicked" : { "unique": 18222 },
                "unsubscribed": { "total" : 3, "percent" : 0.000 },
                "pending" : { "total" : 200, "percent" : 0.011 } ,
                "inProgress" : { "total" : 100, "percent" : 0.005 },
                "sent" : { "total" : 18414, "percent" : 98.397 }
            }


+ Parameters
    + mid (required) ... MID for the account
    + fields (optional, string) ... event fields requested, default is all fields
    + startDate (optional, string) ... ISO8601 formatted Date String, from which to begin collecting events from.  Depending on Precision, this may be rounded to the nearest Day or Hour
    + endDate (optional, string) ... ISO8601 formatted Date string, end time to cap results on.

### Retrieve all Events for an Account [GET]
+ Response 200
    [Account Events][]

## Account Events Daily [/accounts/{mid}/events/daily{?fields,startDate,endDate}]
A collection of events that have occurred for an account, rolled into 24 hour chunks

+ Model (application/json)
    JSON Representation of events that have occurred on an Account, rolled up daily
    + Body
    
            {
                "_links": {
                    "hourly": { "href": "/accounts/{id}/events/hourly{?fields,startDate,endDate}"},
                    "self": { "href": "/accounts/{id}/events/daily{?fields,startDate,endDate}" },
                    "parent": { "href": "/accounts/{id}/events" }
                },
                "id": "{id}",
                "Events": [
                    {
                        "date" : "2014-02-06T07:06:00Z",
                        "toSend": 18714,
                        "delivered": { "total" : 18500, "percent" : 98.85 },
                        "bounces" : { "total" : 164, "hard" : 14, "soft" : 100, "blocked" : 50 },
                        "opened" : { "unique" : 18333 },
                        "clicked" : { "unique": 18222 },
                        "unsubscribed": { "total" : 3, "percent" : 0.000 },
                        "pending" : { "total" : 200, "percent" : 0.011 },
                        "inProgress" : { "total" : 100, "percent" : 0.005 },
                        "sent" : { "total" : 18414, "percent" : 98.397 }
                    },
                    {
                        "date" : "2014-02-05T07:06:00Z",
                        "toSend": 18714,
                        "delivered": { "total" : 18500, "percent" : 98.85 },
                        "bounces" : { "total" : 164, "hard" : 14, "soft" : 100, "blocked" : 50 },
                        "opened" : { "unique" : 18333 },
                        "clicked" : { "unique": 18222 },
                        "unsubscribed": { "total" : 3, "percent" : 0.000 },
                        "pending" : { "total" : 200, "percent" : 0.011 },
                        "inProgress" : { "total" : 100, "percent" : 0.005 },
                        "sent" : { "total" : 18414, "percent" : 98.397 }
                    },
                    {
                        "date" : "2014-02-04T07:06:00Z",
                        "toSend": 18714,
                        "delivered": { "total" : 18500, "percent" : 98.85 },
                        "bounces" : { "total" : 164, "hard" : 14, "soft" : 100, "blocked" : 50 },
                        "opened" : { "unique" : 18333 },
                        "clicked" : { "unique": 18222 },
                        "unsubscribed": { "total" : 3, "percent" : 0.000 },
                        "pending" : { "total" : 200, "percent" : 0.011 }, 
                        "inProgress" : { "total" : 100, "percent" : 0.005 },
                        "sent" : { "total" : 18414, "percent" : 98.397 }
                    }
                ]
            }

+ Parameters
    + mid (required) ... MID for the account
    + fields (optional, string) ... event fields requested, default is all fields
    + startDate (optional, string) ... ISO8601 formatted Date String, from which to begin collecting events from.  Depending on Precision, this may be rounded to the nearest Day or Hour
    + endDate (optional, string) ... ISO8601 formatted Date string, end time to cap results on.

### Retrieve Events for an Account with daily precision [GET]
+ Response 200
    [Account Events Daily][]

## Account Events Hourly [/accounts/{mid}/events/hourly{?fields,startDate,endDate}]
+ Model (application/json)
    JSON Representation of events that have occurred on an Account, rolled up hourly.
    + Body
    
            {
                "_links": {
                    "daily": { "href": "/accounts/{id}/events/daily{?fields,startDate,endDate}"},
                    "self": { "href": "/accounts/{id}/events/hourly{?fields,startDate,endDate}" },
                    "parent": { "href": "/accounts/{id}/events" }
                },
                "Events": [
                    {
                        "date" : "2014-02-04T01:00:00Z",
                        "toSend": 18714,
                        "delivered": { "total" : 18500, "percent" : 98.85 },
                        "bounces" : { "total" : 164, "hard" : 14, "soft" : 100, "blocked" : 50 },
                        "opened" : { "unique" : 18333 },
                        "clicked" : { "unique": 18222 },
                        "unsubscribed": { "total" : 3, "percent" : 0.000 },
                        "pending" : { "total" : 200, "percent" : 0.011 } ,
                        "inProgress" : { "total" : 100, "percent" : 0.005 },
                        "sent" : { "total" : 18414, "percent" : 98.397 }
                    },
                    {
                        "date" : "2014-02-04T02:00:00Z",
                        "toSend": 18714,
                        "delivered": { "total" : 18500, "percent" : 98.85 },
                        "bounces" : { "total" : 164, "hard" : 14, "soft" : 100, "blocked" : 50 },
                        "opened" : { "unique" : 18333 },
                        "clicked" : { "unique": 18222 },
                        "unsubscribed": { "total" : 3, "percent" : 0.000 },
                        "pending" : { "total" : 200, "percent" : 0.011 } ,
                        "inProgress" : { "total" : 100, "percent" : 0.005 },
                        "sent" : { "total" : 18414, "percent" : 98.397 }
                    },
                    {
                        "date" : "2014-02-04T03:00:00Z",
                        "toSend": 18714,
                        "delivered": { "total" : 18500, "percent" : 98.85 },
                        "bounces" : { "total" : 164, "hard" : 14, "soft" : 100, "blocked" : 50 },
                        "opened" : { "unique" : 18333 },
                        "clicked" : { "unique": 18222 },
                        "unsubscribed": { "total" : 3, "percent" : 0.000 },
                        "pending" : { "total" : 200, "percent" : 0.011 } ,
                        "inProgress" : { "total" : 100, "percent" : 0.005 },
                        "sent" : { "total" : 18414, "percent" : 98.397 }
                    }
                ]
            }

+ Parameters
    + mid (required) ... MID for the account
    + fields (optional, string) ... event fields requested, default is all fields
    + startDate (optional, string) ... ISO8601 formatted Date String, from which to begin collecting events from.  Depending on Precision, this may be rounded to the nearest Day or Hour
    + endDate (optional, string) ... ISO8601 formatted Date string, end time to cap results on.

### Retrieve Events for an Account, with Hourly precision [GET]

+ Response 200
    [Account Events Hourly][]


# Group Jobs resource

## Jobs Events [/jobs/{id}/events{?fields}]
A single Event object belonging to a job.

+ Parameters
    + id (required, number, `123`) ... Numeric `id` of the Job to retrieve events from
    + fields (optional, string, `sent,delivered,bouncesHard,bouncesSoft,bouncesBLocked,uniqueOpened,uniqueClicked,unsubscribed` ) ... Comma Separated string of event fields to be returned. 

+ Model (application/json)
    JSON Representation of events that have occurred on a job.
    + Body
    
            {
                "_links": {
                    "self": { "href": "/jobs/{id}/events" },
                    "parent": { "href": "/jobs/{id}" }
                },
                "id": "{id}",
                "total": {
                    "toSend": 18714,
                    "delivered": { "total" : 18500, "percent" : 98.85 },
                    "bounces" : { "total" : 164, "hard" : 14, "soft" : 100, "blocked" : 50 },
                    "opened" : { "unique" : 18333 },
                    "clicked" : { "unique": 18222 },
                    "unsubscribed": { "total" : 3, "percent" : 0.000 },
                    "pending" : { "total" : 200, "percent" : 0.011 } ,
                    "inProgress" : { "total" : 100, "percent" : 0.005 },
                    "sent" : { "total" : 18414, "percent" : 98.397 }
                }
            }

### Retrieve Events for a job [GET]
+ Response 200
    [Jobs Events][]

# Group Message Resource


## Message Events [/message/{id}/events{?fields,startDate,endDate}]
A collection of all events that have occurred for a message, total.

+ Model (application/json)
    JSON Representation of events that have occurred on a Message, rolled up daily
    + Body
    
            {
                "_links": {
                    "daily": { "href": "/message/{id}/events/daily{?fields,startDate,endDate}"},
                    "hourly": { "href": "/message/{id}/events/hourly{?fields,startDate,endDate}"},
                    "self": { "href": "/message/{id}/events{?fields,startDate,endDate}" },
                    "parent": { "href": "/message/{id}" }
                },
                "id": "{id}",
                "toSend": 18714,
                "delivered": { "total" : 18500, "percent" : 98.85 },
                "bounces" : { "total" : 164, "hard" : 14, "soft" : 100, "blocked" : 50 },
                "opened" : { "unique" : 18333 },
                "clicked" : { "unique": 18222 },
                "unsubscribed": { "total" : 3, "percent" : 0.000 },
                "pending" : { "total" : 200, "percent" : 0.011 },
                "inProgress" : { "total" : 100, "percent" : 0.005 },
                "sent" : { "total" : 18414, "percent" : 98.397 }
            }


+ Parameters
    + id (required) ... id for the message
    + fields (optional, string) ... event fields requested, default is all fields
    + startDate (optional, string) ... ISO8601 formatted Date String, from which to begin collecting events from.  Depending on Precision, this may be rounded to the nearest Day or Hour
    + endDate (optional, string) ... ISO8601 formatted Date string, end time to cap results on.

### Retrieve all Events for a Message [GET]
+ Response 200
    [Message Events][]

## Message Events Daily [/message/{id}/events/daily{?fields,startDate,endDate}]
A collection of events that have occurred for a message, rolled into 24 hour chunks

+ Model (application/json)
    JSON Representation of events that have occurred on a Message, rolled up daily
    + Body
    
            {
                "_links": {
                    "hourly": { "href": "/message/{id}/events/hourly{?fields,startDate,endDate}"},
                    "self": { "href": "/message/{id}/events/daily{?fields,startDate,endDate}" },
                    "parent": { "href": "/message/{id}/events" }
                },
                "id": "{id}",
                "Events": [
                    {
                        "date" : "2014-02-06T07:06:00Z",
                        "toSend": 18714,
                        "delivered": { "total" : 18500, "percent" : 98.85 },
                        "bounces" : { "total" : 164, "hard" : 14, "soft" : 100, "blocked" : 50 },
                        "opened" : { "unique" : 18333 },
                        "clicked" : { "unique": 18222 },
                        "unsubscribed": { "total" : 3, "percent" : 0.000 },
                        "pending" : { "total" : 200, "percent" : 0.011 } ,
                        "inProgress" : { "total" : 100, "percent" : 0.005 },
                        "sent" : { "total" : 18414, "percent" : 98.397 }
                    },
                    {
                        "date" : "2014-02-05T07:06:00Z",
                        "toSend": 18714,
                        "delivered": { "total" : 18500, "percent" : 98.85 },
                        "bounces" : { "total" : 164, "hard" : 14, "soft" : 100, "blocked" : 50 },
                        "opened" : { "unique" : 18333 },
                        "clicked" : { "unique": 18222 },
                        "unsubscribed": { "total" : 3, "percent" : 0.000 },
                        "pending" : { "total" : 200, "percent" : 0.011 } ,
                        "inProgress" : { "total" : 100, "percent" : 0.005 },
                        "sent" : { "total" : 18414, "percent" : 98.397 }
                    },
                    {
                        "date" : "2014-02-04T07:06:00Z",
                        "toSend": 18714,
                        "delivered": { "total" : 18500, "percent" : 98.85 },
                        "bounces" : { "total" : 164, "hard" : 14, "soft" : 100, "blocked" : 50 },
                        "opened" : { "unique" : 18333 },
                        "clicked" : { "unique": 18222 },
                        "unsubscribed": { "total" : 3, "percent" : 0.000 },
                        "pending" : { "total" : 200, "percent" : 0.011 } ,
                        "inProgress" : { "total" : 100, "percent" : 0.005 },
                        "sent" : { "total" : 18414, "percent" : 98.397 }
                    }
                ]
            }

+ Parameters
    + id (required) ... id for the message
    + fields (optional, string) ... event fields requested, default is all fields
    + startDate (optional, string) ... ISO8601 formatted Date String, from which to begin collecting events from.  Depending on Precision, this may be rounded to the nearest Day or Hour
    + endDate (optional, string) ... ISO8601 formatted Date string, end time to cap results on.

### Retrieve Events for a Message with daily precision [GET]
+ Response 200
    [Message Events Daily][]

## Message Events Hourly [/message/{id}/events/hourly{?fields,startDate,endDate}]
+ Model (application/json)
    JSON Representation of events that have occurred on a Message, rolled up hourly.
    + Body
    
            {
                "_links": {
                    "daily": { "href": "/message/{id}/events/daily{?fields,startDate,endDate}"},
                    "self": { "href": "/message/{id}/events/hourly{?fields,startDate,endDate}" },
                    "parent": { "href": "/message/{id}/events" }
                },
                "Events": [
                    {
                        "date" : "2014-02-04T01:00:00Z",
                        "toSend": 18714,
                        "delivered": { "total" : 18500, "percent" : 98.85 },
                        "bounces" : { "total" : 164, "hard" : 14, "soft" : 100, "blocked" : 50 },
                        "opened" : { "unique" : 18333 },
                        "clicked" : { "unique": 18222 },
                        "unsubscribed": { "total" : 3, "percent" : 0.000 },
                        "pending" : { "total" : 200, "percent" : 0.011 } ,
                        "inProgress" : { "total" : 100, "percent" : 0.005 },
                        "sent" : { "total" : 18414, "percent" : 98.397 }
                    },
                    {
                        "date" : "2014-02-04T02:00:00Z",
                        "toSend": 18714,
                        "delivered": { "total" : 18500, "percent" : 98.85 },
                        "bounces" : { "total" : 164, "hard" : 14, "soft" : 100, "blocked" : 50 },
                        "opened" : { "unique" : 18333 },
                        "clicked" : { "unique": 18222 },
                        "unsubscribed": { "total" : 3, "percent" : 0.000 },
                        "pending" : { "total" : 200, "percent" : 0.011 } ,
                        "inProgress" : { "total" : 100, "percent" : 0.005 },
                        "sent" : { "total" : 18414, "percent" : 98.397 }
                    },
                    {
                        "date" : "2014-02-04T03:00:00Z",
                        "toSend": 18714,
                        "delivered": { "total" : 18500, "percent" : 98.85 },
                        "bounces" : { "total" : 164, "hard" : 14, "soft" : 100, "blocked" : 50 },
                        "opened" : { "unique" : 18333 },
                        "clicked" : { "unique": 18222 },
                        "unsubscribed": { "total" : 3, "percent" : 0.000 },
                        "pending" : { "total" : 200, "percent" : 0.011 } ,
                        "inProgress" : { "total" : 100, "percent" : 0.005 },
                        "sent" : { "total" : 18414, "percent" : 98.397 }
                    }
                ]
            }

+ Parameters
    + id (required) ... id for the message
    + fields (optional, string) ... event fields requested, default is all fields
    + startDate (optional, string) ... ISO8601 formatted Date String, from which to begin collecting events from.  Depending on Precision, this may be rounded to the nearest Day or Hour
    + endDate (optional, string) ... ISO8601 formatted Date string, end time to cap results on.

### Retrieve Events for a Message, with Hourly precision [GET]

+ Response 200
    [Message Events Hourly][]

## Message Email Preview [/messages/{id}/preview]
Email preview for message jobs

+ Parameters
    + id (required) ... id for the message.  Could be a Triggered Send or an Email Send Definition id.

+ Model (application/json)
    JSON Representation of the email preview for all jobs associated to a message
    + Body
    
            {
                "id": "{id}",
                "Previews": [
                    {
                        "jobId": "654231",
                        "mostRecent": 1,
                        "encodedHtml": "",
                        "encodedText": ""
                    },
                    {
                        "jobId": "45642",
                        "mostRecent": 0,
                        "encodedHtml": "",
                        "encodedText": ""
                    },
                    {
                        "jobId": "5642",
                        "mostRecent": 0,
                        "encodedHtml": "",
                        "encodedText": ""
                    }
                ]
            }

### Retrieve Email Previews for a Message [GET]
+ Response 200
    [Message Email Preview][]

