FORMAT: 1A
HOST: http://www.exacttargetapis.com/

# Jobs Events API
Method for retrieving Event information from a single job.

# Group Events

## Jobs Events [/jobs/{id}/events{?fields}]
A single Event object belonging to a job.

+ Parameters
    + id (required, number, `123`) ... Numeric `id` of the Job to retrieve events from
    + fields (optional, string, `sent,delivered,bouncesHard,bouncesSoft,bouncesBLocked,uniqueOpened,uniqueClicked,unsubscribed` ) ... Comma Separated string of event fields to be returned. 

+ Model (application/json)
    JSON Representation of events that have occurred on a job.
    + Body
    
            {
                "_links": {
                    "self": { "href": "/jobs/123/events" },
                    "parent": { "href": /jobs/123" }
                },
                "id": "123",
                "total": {
                    "sent": 18714,
                    "delivered": 18500,
                    "bouncesHard": 14,
                    "bouncesSoft": 100,
                    "bouncesBlocked": 50,
                    "uniqueOpened": 18333,
                    "uniqueClicked": 18222,
                    "unsubscribed": 3
                }
            }

### Retrieve Events for a job [GET]
+ Response 200
    [Jobs Events][]

## Account Events [/account/{mid}/events{?fields&startDate&endDate&precision]
A collection of events that have occurred for an account

+ Parameters
    + mid (required) ... MID for the account
    + fields (optional, string) ... event fields requested, default is all fields
    + startDate (optional, string) ... ISO8601 formatted Date String, from which to begin collecting events from.  Depending on Precision, this may be rounded to the nearest Day or Hour
    + endDate (optional, string) ... ISO8601 formatted Date string, end time to cap results on.
    + precision (optional, string, `[day,hour,all]`) ... Precision with which to collate results.


